spring:
  data:
    cassandra:
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s


  config:
    import: secure.yml

datastax.astra:
  secure-connect-bundle: secure-connect-betterreads.zip


